# ==========================
# ❓ ʏᴀʀᴅıᴍ ᴍᴇɴᴜsᴜ (sᴘᴀᴍ ᴋᴏʀᴜᴍᴀʟı) EN AŞAĞIDAKİ KODLARA BAKIN BURDAKİ!!!!!! yazan kod kod
# ==========================

command /yardım:
    aliases: /help, /bilgi
    trigger:
        # 2 Saniye Bekleme Suresi
        set {_waited} to difference between {cd::yardim::%player%} and now
        if {_waited} is less than 2 seconds:
            set {_kalan} to 2 - floor(unix timestamp of now - unix timestamp of {cd::yardim::%player%})
            send action bar "&cʙᴇᴋʟᴇᴍᴇʟısıɴ: &e%{_kalan}%sɴ" to player
            stop
            
        set {cd::yardim::%player%} to now
        set {_gui} to a new chest inventory with 3 rows named "&8&nsısᴛᴇᴍʟᴇʀ ᴠᴇ ᴋᴏᴍᴜᴛʟᴀʀ"
        
        loop 27 times:
            set slot (loop-number - 1) of {_gui} to black stained glass pane named "&8"
        
        set {_lore1::*} to "" and "&6/ʀᴛᴘ &f- &7ʀᴀsᴛɢᴇʟᴇ ısıɴʟᴀɴ" and "&6/ᴍᴀʀᴋᴇᴛ &f- &7ᴍᴀʀᴋᴇᴛı ᴀᴄᴀʀ" and "&6/ᴀʜ &f- &7ᴏʏᴜɴᴄᴜ ᴘᴀᴢᴀʀı" and "&6/sᴀᴛ &f- &7ᴇsʏᴀ sᴀᴛ" and "&6/ʜᴏᴍᴇ &f- &7ᴇᴠʟᴇʀıɴ" and "&6/ᴋıᴛ &f- &7ᴋıᴛʟᴇʀıɴı ᴀʟ" and "&6/ᴛᴀᴋᴀs &f- &7ɢᴜᴠᴇɴʟı ᴛᴀᴋᴀs"
        set slot 11 of {_gui} to netherite_sword named "&9&lɢᴇɴᴇʟ ᴋᴏᴍᴜᴛʟᴀʀ" with lore {_lore1::*}
        
        set {_lore2::*} to "" and "&6/ᴋʀısᴛᴀʟ &f- &7ᴋʀısᴛᴀʟ ᴍᴀʀᴋᴇᴛ" and "&6/ʀᴜᴛʙᴇ &f- &7ʀᴜᴛʙᴇ ᴀᴛʟᴀ" and "&6/ɢᴜɴʟᴜᴋᴏᴅᴜʟ &f- &7ᴏᴅᴜʟᴜɴᴜ ᴋᴀᴘ" and "&6/ᴀʏᴀʀʟᴀʀ &f- &7ᴋısısᴇʟ ᴛᴇʀᴄıʜ" and "&6/ᴀғᴋ &f- &7ᴀғᴋ ᴀʟᴀɴıɴᴀ ɢıᴛ"
        set slot 13 of {_gui} to emerald named "&a&lᴏᴢᴇʟ sısᴛᴇᴍʟᴇʀ" with lore {_lore2::*}
        
        set {_lore3::*} to "" and "&6/ᴛᴇᴀᴍ ᴄʀᴇᴀᴛᴇ &f- &7ᴛᴀᴋıᴍ ᴋᴜʀ" and "&6/ᴛᴇᴀᴍ ıɴᴠıᴛᴇ &f- &7ᴜʏᴇ ᴄᴀɢıʀ" and "&6/ᴛᴇᴀᴍ sᴇᴛʜᴏᴍᴇ &f- &7ᴜss ʙᴇʟıʀʟᴇ" and "&6/ᴛᴇᴀᴍ ʜᴏᴍᴇ &f- &7ᴜssᴇ ɢıᴛ" and "&6/ᴛᴇᴀᴍ ᴇᴄʜᴇsᴛ &f- &7ᴏʀᴛᴀᴋ ᴅᴇᴘᴏ"
        set slot 15 of {_gui} to shield named "&b&lᴛᴀᴋıᴍ sısᴛᴇᴍı" with lore {_lore3::*}
        
        set slot 26 of {_gui} to barrier named "&4&lᴋᴀᴘᴀᴛ" with lore "&7ᴍᴇɴᴜʏᴜ ᴋᴀᴘᴀᴛᴍᴀᴋ ıᴄıɴ ᴛıᴋʟᴀ!"

        open {_gui} to player

on inventory click:
    if name of event-inventory is "&8&nsısᴛᴇᴍʟᴇʀ ᴠᴇ ᴋᴏᴍᴜᴛʟᴀʀ":
        cancel event
        if index of event-slot is 26:
            close player's inventory



# BURADAKİ!!!!!!!!!!!!!!!!!!! /rtp /market vb şeyleri kendiniz yaparak değiştirebilirsiniz set {_lore1::*} to "" and "&6/ʀᴛᴘ &f- &7ʀᴀsᴛɢᴇʟᴇ ısıɴʟᴀɴ" and "&6/ᴍᴀʀᴋᴇᴛ &f- &7ᴍᴀʀᴋᴇᴛı ᴀᴄᴀʀ" and "&6/ᴀʜ &f- &7ᴏʏᴜɴᴄᴜ ᴘᴀᴢᴀʀı" and "&6/sᴀᴛ &f- &7ᴇsʏᴀ sᴀᴛ" and "&6/ʜᴏᴍᴇ &f- &7ᴇᴠʟᴇʀıɴ" and "&6/ᴋıᴛ &f- &7ᴋıᴛʟᴇʀıɴı ᴀʟ" and "&6/ᴛᴀᴋᴀs &f- &7ɢᴜᴠᴇɴʟı ᴛᴀᴋᴀs"
        set slot 11 of {_gui} to netherite_sword named "&9&lɢᴇɴᴇʟ ᴋᴏᴍᴜᴛʟᴀʀ" with lore {_lore1::*}
        
        set {_lore2::*} to "" and "&6/ᴋʀısᴛᴀʟ &f- &7ᴋʀısᴛᴀʟ ᴍᴀʀᴋᴇᴛ" and "&6/ʀᴜᴛʙᴇ &f- &7ʀᴜᴛʙᴇ ᴀᴛʟᴀ" and "&6/ɢᴜɴʟᴜᴋᴏᴅᴜʟ &f- &7ᴏᴅᴜʟᴜɴᴜ ᴋᴀᴘ" and "&6/ᴀʏᴀʀʟᴀʀ &f- &7ᴋısısᴇʟ ᴛᴇʀᴄıʜ" and "&6/ᴀғᴋ &f- &7ᴀғᴋ ᴀʟᴀɴıɴᴀ ɢıᴛ"
        set slot 13 of {_gui} to emerald named "&a&lᴏᴢᴇʟ sısᴛᴇᴍʟᴇʀ" with lore {_lore2::*}
        
        set {_lore3::*} to "" and "&6/ᴛᴇᴀᴍ ᴄʀᴇᴀᴛᴇ &f- &7ᴛᴀᴋıᴍ ᴋᴜʀ" and "&6/ᴛᴇᴀᴍ ıɴᴠıᴛᴇ &f- &7ᴜʏᴇ ᴄᴀɢıʀ" and "&6/ᴛᴇᴀᴍ sᴇᴛʜᴏᴍᴇ &f- &7ᴜss ʙᴇʟıʀʟᴇ" and "&6/ᴛᴇᴀᴍ ʜᴏᴍᴇ &f- &7ᴜssᴇ ɢıᴛ" and "&6/ᴛᴇᴀᴍ ᴇᴄʜᴇsᴛ &f- &7ᴏʀᴛᴀᴋ ᴅᴇᴘᴏ"
        set slot 15 of {_gui} to shield named "&b&lᴛᴀᴋıᴍ sısᴛᴇᴍı" with lore {_lore3::*}
        
        set slot 26 of {_gui} to barrier named "&4&lᴋᴀᴘᴀᴛ" with lore "&7ᴍᴇɴᴜʏᴜ ᴋᴀᴘᴀᴛᴍᴀᴋ ıᴄıɴ ᴛıᴋʟᴀ!"

